---

- name: download docker_sd binary archive
  become: false
  delegate_to: "{{ docker_sd_delegate_to }}"
  run_once: "{{ 'false' if docker_sd_direct_download else 'true' }}"
  ansible.builtin.get_url:
    url: "{{ docker_sd_release_download_url }}/download/{{ __docker_sd_files.archive }}"
    dest: "{{ docker_sd_local_tmp_directory }}/docker_sd-linux-amd64.tar.gz"
    checksum: "sha256:{{ __docker_sd_checksum }}"
    mode: 0660
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract docker_sd archive
  become: false
  delegate_to: "{{ docker_sd_delegate_to }}"
  run_once: "{{ 'false' if docker_sd_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ docker_sd_local_tmp_directory }}/docker_sd-linux-amd64.tar.gz"
    dest: "{{ docker_sd_local_tmp_directory }}"
    copy: false
  register: _extract_archive

...
