---

- name: user and group handling
  when:
    - docker_sd_system_user != "root" or docker_sd_system_group != "root"
  block:
    - name: create docker-sd group
      ansible.builtin.group:
        name: "{{ docker_sd_system_group }}"
        state: present
        system: true
      when:
        - docker_sd_system_group != "root"

    - name: create docker-sd user
      ansible.builtin.user:
        name: "{{ docker_sd_system_user }}"
        groups: "{{ docker_sd_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent
      when:
        - docker_sd_system_user != "root"

- name: create install directory
  ansible.builtin.file:
    path: "{{ docker_sd_install_path }}"
    state: directory
    owner: "{{ docker_sd_system_user }}"
    group: "{{ docker_sd_system_group }}"
    mode: 0755

- name: detect extracted binary file for docker_sd on '{{ docker_sd_delegate_to }}'
  become: false
  delegate_to: "{{ docker_sd_delegate_to }}"
  run_once: "{{ 'false' if docker_sd_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ docker_sd_local_tmp_directory }}/{{ docker_sd_release.binary }}"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: detect installed docker_sd binary
  ansible.builtin.stat:
    path: "{{ docker_sd_install_path }}/{{ docker_sd_release.binary }}"
  register: stat_docker_sd_binary

- name: detect activated docker_sd binary
  ansible.builtin.stat:
    path: /usr/bin/{{ docker_sd_release.binary }}
  register: stat_docker_sd_activated

- name: install and activate docker_sd
  when:
    - stat_docker_sd_binary.stat is defined
    - not stat_docker_sd_binary.stat.exists | default('false')
    - stat_docker_sd_activated.stat is defined
    - not stat_docker_sd_activated.stat.exists | default('false')
  block:
    - name: propagate files
      block:
        - name: propagate docker_sd binaries
          ansible.builtin.copy:
            src: "{{ docker_sd_local_tmp_directory }}/{{ docker_sd_release.binary }}"
            dest: "{{ docker_sd_install_path }}/{{ docker_sd_release.binary }}"
            mode: 0755
            owner: "{{ docker_sd_system_user }}"
            group: "{{ docker_sd_system_group }}"
            remote_src: "{{ 'true' if docker_sd_direct_download else 'false' }}"

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ docker_sd_install_path }}/{{ docker_sd_release.binary }}"
            dest: "/usr/bin/{{ docker_sd_release.binary }}"
            state: link
            force: true
            follow: false
          notify:
            - restart docker-sd

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ docker_sd_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: create docker_sd configuration directory
  ansible.builtin.file:
    path: "{{ docker_sd_config_dir }}"
    state: directory
    owner: root
    group: "{{ docker_sd_system_group }}"
    mode: 0770

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create docker-sd system configuration
      ansible.builtin.template:
        src: "default/docker-sd.j2"
        dest: "{{ docker_sd_defaults_directory }}/docker-sd"
        force: true
        owner: root
        group: "{{ docker_sd_system_group }}"
        mode: 0640
      notify:
        - restart docker-sd

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/docker-sd.service.j2"
        dest: "{{ systemd_lib_directory }}/docker-sd.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/docker-sd.j2"
        dest: "/etc/conf.d/docker-sd"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/docker-sd.j2"
        dest: "/etc/init.d/docker-sd"
        owner: root
        group: root
        mode: 0750

- name: create custom fact file
  bodsch.core.facts:
    name: docker_sd
    facts:
      version: "{{ docker_sd_version }}"

...
