---

- name: detect binary file for docker-sd - {{ docker_sd_local_tmp_directory }}/docker-sd
  become: false
  delegate_to: "{{ docker_sd_delegate_to }}"
  run_once: "{{ 'false' if docker_sd_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ docker_sd_local_tmp_directory }}/docker-sd"
  register: stat_file_binary

- name: install docker-sd
  when:
    - stat_file_binary.stat.exists
  block:
    - name: propagate docker-sd binary
      ansible.builtin.copy:
        src: "{{ docker_sd_local_tmp_directory }}/docker-sd"
        dest: "{{ docker_sd_install_path }}/docker-sd"
        mode: 0755
        owner: "{{ docker_sd_system_user }}"
        group: "{{ docker_sd_system_group }}"
        remote_src: "{{ 'true' if docker_sd_direct_download else 'false' }}"

    - name: make files executable
      ansible.builtin.file:
        path: "{{ docker_sd_install_path }}/docker-sd"
        mode: 0755
        owner: "{{ docker_sd_system_user }}"
        group: "{{ docker_sd_system_group }}"

- name: create local facts
  ansible.builtin.template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/docker_sd.fact
    mode: 0755

- name: create link to binary
  ansible.builtin.file:
    src: "{{ docker_sd_install_path }}/docker-sd"
    dest: /usr/bin/docker-sd
    state: link
    force: true
    follow: false
  notify:
    - restart docker-sd

- name: create systemd service unit
  ansible.builtin.template:
    src: "init/systemd/docker-sd.service.j2"
    dest: "{{ systemd_lib_directory }}/docker-sd.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
    - restart docker-sd

...
