---

- name: This repository will therefore no longer be actively maintained.
  ansible.builtin.fail:
    msg: |
      Further development of this Ansible role has been moved to Collection bodsch.prometheus.
      This repository will therefore no longer be actively maintained.
  ignore_errors: true

- name: wait 10 seconds to realise the message
  delegate_to: localhost
  ansible.builtin.wait_for:
    timeout: 10

- name: include OS specific configuration. ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yaml
      skip: true

- name: install dependency
  ansible.builtin.package:
    name: "{{ docker_sd_requirements }}"
    state: present
  when:
    - docker_sd_requirements | default([]) | count > 0

- name: merge docker-sd configuration between defaults and custom
  ansible.builtin.set_fact:
    docker_sd_rest_api: "{{ docker_sd_defaults_rest_api | combine(docker_sd_rest_api, recursive=True) }}"
    docker_sd_hosts: "{{ docker_sd_defaults_hosts | union(docker_sd_hosts) }}"
    docker_sd_addition_labels: "{{ docker_sd_defaults_addition_labels | union(docker_sd_addition_labels) }}"

...
