---

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: ensure docker-sd is enabled on boot
  become: true
  ansible.builtin.service:
    name: docker-sd
    enabled: true
    state: started

...
